### ISSUE TITLE
[no-http-string]: ignore namespace URIs

### ISSUE THREAD

**Issue by ElPrudi** [microsoft/eslint-plugin-powerbi-visuals#10]
### Info
**package version**:  0.8.1

### How to reproduce:
```
const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg')
```
[Other important namespace URIs](https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS#important_namespace_uris)
### Current workaround
```
 "powerbi-visuals/no-http-string": [2, "^http:\\/\\/www.w3.org\\/2000\\/svg"]
```
<br>
It would be great to use these namespace URIs without specifying them in the eslintrc options.

**Comment by AleksSavelev** [comment]
It's now added to the latest version of plugin
